import { NextResponse } from "next/server";
import { getRequestIdentity } from "@/lib/auth/request-identity";
import { createNextAction, listNextActions } from "@/lib/professional-next-action-repository";
import { getPlanAccess,hasVelvetFeature } from "@/lib/plan-access";
import { INPUT_LIMITS } from "@/lib/input-limits";

function observability(request:Request){const traceId=request.headers.get("x-trace-id")??crypto.randomUUID();const correlationId=request.headers.get("x-correlation-id")??traceId;const requestId=request.headers.get("x-request-id")??crypto.randomUUID();return{traceId,correlationId,requestId}}
async function requireAccess(ownerUserId:string,request:Request){const access=await getPlanAccess(ownerUserId);return hasVelvetFeature(access,"followup.manage")?null:NextResponse.json({status:"error",error:{code:"PRO_REQUIRED",message:"Next Action is available on Pro."},plan:access.plan,...observability(request)},{status:403})}
type DueAtParse={dueAt?:string;error?:string};
function parseDueAt(value:unknown):DueAtParse{if(value===undefined||value===null||value==="")return{};if(typeof value!=="string")return{error:"dueAt must be an ISO date-time string"};const date=new Date(value);if(!Number.isFinite(date.getTime()))return{error:"dueAt must be a valid ISO date-time string"};return{dueAt:date.toISOString()}}

export async function GET(request:Request,{params}:{params:Promise<{customerId:string}>}){const {workspaceId,userId,ownerUserId}=await getRequestIdentity();const denied=await requireAccess(ownerUserId,request);if(denied)return denied;const {customerId}=await params;const items=await listNextActions(workspaceId,userId,customerId);return NextResponse.json({status:"success",customerId,items,...observability(request)})}

export async function POST(request:Request,{params}:{params:Promise<{customerId:string}>}){const {workspaceId,userId,ownerUserId}=await getRequestIdentity();const denied=await requireAccess(ownerUserId,request);if(denied)return denied;const {customerId}=await params;const obs=observability(request);const body=await request.json().catch(()=>({})) as Record<string,unknown>;for(const key of ["salesAmount","paymentStatus","paymentMethod","stripe","customer"]){if(key in body)return NextResponse.json({status:"error",error:{code:"PROHIBITED_FIELDS",message:`${key} is not accepted by VelvetNextAction.Create`},...obs},{status:400})}const text=typeof body.text==="string"?body.text.trim():"";if(!text)return NextResponse.json({status:"error",error:{code:"NEXT_ACTION_REQUIRED",message:"text is required"},...obs},{status:400});if(text.length>INPUT_LIMITS.nextAction)return NextResponse.json({status:"error",error:{code:"NEXT_ACTION_TOO_LONG",message:`text must be ${INPUT_LIMITS.nextAction} characters or fewer`},...obs},{status:400});const due=parseDueAt(body.dueAt);if(due.error)return NextResponse.json({status:"error",error:{code:"INVALID_DUE_AT",message:due.error},...obs},{status:400});const item=await createNextAction(workspaceId,userId,customerId,text,due.dueAt);return NextResponse.json({status:"success",customerId,nextActionId:item.id,nextActionRef:`velvet:next-action:${item.id}`,dueAt:item.dueAt,eventName:"velvet.next_action.created.v1",...obs},{status:201})}
