import { NextResponse } from "next/server";
import { getRequestIdentity } from "@/lib/auth/request-identity";
import { createNextAction, listNextActions } from "@/lib/professional-next-action-repository";

function observability(request:Request){const traceId=request.headers.get("x-trace-id")??crypto.randomUUID();const correlationId=request.headers.get("x-correlation-id")??traceId;const requestId=request.headers.get("x-request-id")??crypto.randomUUID();return{traceId,correlationId,requestId}}

export async function GET(request:Request,{params}:{params:Promise<{customerId:string}>}){const {workspaceId,userId}=await getRequestIdentity();const {customerId}=await params;const items=await listNextActions(workspaceId,userId,customerId);return NextResponse.json({status:"success",customerId,items,...observability(request)})}

export async function POST(request:Request,{params}:{params:Promise<{customerId:string}>}){const {workspaceId,userId}=await getRequestIdentity();const {customerId}=await params;const obs=observability(request);const body=await request.json().catch(()=>({})) as Record<string,unknown>;for(const key of ["salesAmount","paymentStatus","paymentMethod","stripe","customer"]){if(key in body)return NextResponse.json({status:"error",error:{code:"PROHIBITED_FIELDS",message:`${key} is not accepted by VelvetNextAction.Create`},...obs},{status:400})}const text=typeof body.text==="string"?body.text.trim():"";if(!text)return NextResponse.json({status:"error",error:{code:"NEXT_ACTION_REQUIRED",message:"text is required"},...obs},{status:400});const item=await createNextAction(workspaceId,userId,customerId,text);return NextResponse.json({status:"success",customerId,nextActionId:item.id,nextActionRef:`velvet:next-action:${item.id}`,eventName:"velvet.next_action.created.v1",...obs},{status:201})}
