import Link from "next/link";
import { BottomNav } from "@/components/bottom-nav";
import { getRequestIdentity } from "@/lib/auth/request-identity";
import { listScheduleEntries } from "@/lib/schedule-repository";
import { listGrowthCustomers } from "@/lib/growth-engine-customer";
import { createScheduleAction } from "./actions";

const kindLabel={shift:"出勤",visit:"来店",birthday:"誕生日",unavailable:"予定あり",self_investment:"自分の予定",other:"その他"} as const;
const day=(value:string)=>new Intl.DateTimeFormat("ja-JP",{month:"numeric",day:"numeric",weekday:"short"}).format(new Date(value));const time=(value:string)=>new Intl.DateTimeFormat("ja-JP",{hour:"2-digit",minute:"2-digit"}).format(new Date(value));
export default async function SchedulePage({searchParams}:{searchParams:Promise<{saved?:string;error?:string}>}){const {saved,error}=await searchParams;const {workspaceId,userId}=await getRequestIdentity();const [entries,customers]=await Promise.all([listScheduleEntries(workspaceId,userId),listGrowthCustomers(workspaceId,userId)]);const customerById=new Map(customers.map(c=>[c.customerId,c]));const sorted=[...entries].sort((a,b)=>a.startsAt.localeCompare(b.startsAt));return <main className="shell scheduleShell"><header className="header"><div className="brand">予定</div><Link className="subtle" href="/">今日</Link></header>
 {saved&&<div className="card successCard">予定を追加しました</div>}{error==="customer"&&<div className="formError">来店予定は、お客様を選んでください。</div>}{error==="datetime"&&<div className="formError">日時を選んでください。</div>}
 <div className="sectionTitle">これからの予定</div>{sorted.length>0?<div className="stack">{sorted.map(entry=><article className="card" key={entry.id}><div className="row"><div><div className="timelineTitle">{entry.title}</div><div className="personMeta">{day(entry.startsAt)} · {time(entry.startsAt)}</div></div><span className="chip">{kindLabel[entry.kind]}</span></div>{entry.customerId&&<div className="timelineBody">{customerById.get(entry.customerId)?.displayName??"お客様"}</div>}{entry.note&&<div className="formHint">{entry.note}</div>}</article>)}</div>:<div className="card empty">予定はまだありません</div>}
 <details className="detailsCard" open={sorted.length===0||Boolean(error)}><summary>＋ 予定を追加</summary><form action={createScheduleAction} className="stack scheduleForm detailsBody"><div className="chips choiceRow">{(["visit","shift","birthday","unavailable","self_investment","other"] as const).map(kind=><label className="choiceChip" key={kind}><input type="radio" name="kind" value={kind} defaultChecked={kind==="visit"}/>{kindLabel[kind]}</label>)}</div>{customers.length>0&&<select className="selectBox" name="customerId" defaultValue=""><option value="">お客様を選ぶ（来店の時）</option>{customers.map(customer=><option key={customer.customerId} value={customer.customerId}>{customer.displayName}</option>)}</select>}<label className="fieldLabel" htmlFor="startsAt">日時</label><input id="startsAt" className="searchBox" name="startsAt" type="datetime-local"/><input className="searchBox" name="title" placeholder="内容（空欄でもOK）" autoComplete="off"/><input className="searchBox" name="note" placeholder="メモ（必要な時だけ）" autoComplete="off"/><button className="primaryButton" type="submit">予定を追加</button></form></details><BottomNav/></main>}
