import Link from "next/link";
import { AppHeader } from "@/components/app-header";
import { BottomNav } from "@/components/bottom-nav";
import { getRequestIdentity } from "@/lib/auth/request-identity";
import { listScheduleEntries, type ScheduleEntry } from "@/lib/schedule-repository";
import { listGrowthCustomers } from "@/lib/growth-engine-customer";
import { createScheduleAction } from "./actions";

const kindLabel={shift:"出勤",visit:"来店",birthday:"誕生日",unavailable:"約束",self_investment:"自分の予定",other:"その他"} as const;
const kindIcon={shift:"◇",visit:"●",birthday:"🎁",unavailable:"◆",self_investment:"○",other:"・"} as const;
const viewLabel={day:"今日",week:"週間",month:"月間"} as const;
type ScheduleView=keyof typeof viewLabel;
const day=(value:Date|string)=>new Intl.DateTimeFormat("ja-JP",{month:"numeric",day:"numeric",weekday:"short",timeZone:"Asia/Tokyo"}).format(new Date(value));
const time=(value:Date|string)=>new Intl.DateTimeFormat("ja-JP",{hour:"2-digit",minute:"2-digit",timeZone:"Asia/Tokyo"}).format(new Date(value));
const monthTitle=(value:Date)=>new Intl.DateTimeFormat("ja-JP",{year:"numeric",month:"long",timeZone:"Asia/Tokyo"}).format(value);
const tokyoKey=(value:Date|string)=>{const parts=new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Tokyo",year:"numeric",month:"2-digit",day:"2-digit"}).formatToParts(new Date(value));const get=(type:string)=>parts.find(part=>part.type===type)?.value??"";return `${get("year")}-${get("month")}-${get("day")}`};
const tokyoWeekday=(value:Date|string)=>Number(new Intl.DateTimeFormat("en-US",{timeZone:"Asia/Tokyo",weekday:"short"}).format(new Date(value)).replace(/Sun|Mon|Tue|Wed|Thu|Fri|Sat/,m=>String(["Sun","Mon","Tue","Wed","Thu","Fri","Sat"].indexOf(m))));
const startOfTokyoDay=(key:string)=>new Date(`${key}T00:00:00+09:00`);
const addDays=(date:Date,days:number)=>new Date(date.getTime()+days*24*60*60*1000);
const addMonthsTokyo=(date:Date,months:number)=>{const key=tokyoKey(date);const [year,month]=key.split("-").map(Number);return new Date(Date.UTC(year,month-1+months,1)-9*60*60*1000)};
function viewRange(view:ScheduleView,cursor:Date){
  const cursorKey=tokyoKey(cursor);const start=startOfTokyoDay(cursorKey);
  if(view==="day") return {start,end:addDays(start,1),title:day(start),prev:addDays(start,-1),next:addDays(start,1)};
  if(view==="week"){const weekday=tokyoWeekday(cursor);const mondayOffset=(weekday+6)%7;const weekStart=addDays(start,-mondayOffset);const weekEnd=addDays(weekStart,7);return {start:weekStart,end:weekEnd,title:`${day(weekStart)}〜${day(addDays(weekEnd,-1))}`,prev:addDays(weekStart,-7),next:weekEnd}}
  const [year,month]=cursorKey.split("-").map(Number);const monthStart=new Date(Date.UTC(year,month-1,1)-9*60*60*1000);const monthEnd=new Date(Date.UTC(year,month,1)-9*60*60*1000);return {start:monthStart,end:monthEnd,title:monthTitle(monthStart),prev:addMonthsTokyo(monthStart,-1),next:addMonthsTokyo(monthStart,1)};
}
function monthCells(monthStart:Date){
  const startKey=tokyoKey(monthStart);const [,month]=startKey.split("-").map(Number);const firstWeekday=tokyoWeekday(monthStart);const firstCell=addDays(monthStart,-firstWeekday);return Array.from({length:42},(_,index)=>{const date=addDays(firstCell,index);const key=tokyoKey(date);const [,cellMonth,cellDay]=key.split("-").map(Number);return {date,key,day:cellDay,currentMonth:cellMonth===month,today:key===tokyoKey(new Date())};});
}
const scheduleHref=(view:ScheduleView,cursor:Date)=>`/schedule?view=${view}&cursor=${tokyoKey(cursor)}`;
const entriesForDay=(entries:ScheduleEntry[],key:string)=>entries.filter(entry=>tokyoKey(entry.startsAt)===key);

export default async function SchedulePage({searchParams}:{searchParams:Promise<{saved?:string;error?:string;view?:string;cursor?:string}>}){
 const {saved,error,view:rawView,cursor}=await searchParams;const view:ScheduleView=rawView==="week"||rawView==="month"?rawView:"day";const cursorDate=cursor&&/^\d{4}-\d{2}-\d{2}$/.test(cursor)?startOfTokyoDay(cursor):new Date();const {workspaceId,userId}=await getRequestIdentity();const [entries,customers]=await Promise.all([listScheduleEntries(workspaceId,userId),listGrowthCustomers(workspaceId,userId)]);const customerById=new Map(customers.map(c=>[c.customerId,c]));const sorted=[...entries].sort((a,b)=>a.startsAt.localeCompare(b.startsAt));const range=viewRange(view,cursorDate);const visible=sorted.filter(entry=>{const value=new Date(entry.startsAt).getTime();return value>=range.start.getTime()&&value<range.end.getTime()});const monthGrid=view==="month"?monthCells(range.start):[];
 const renderEntry=(entry:ScheduleEntry)=>{const customer=entry.customerId?customerById.get(entry.customerId):undefined;return <article className={`card scheduleEntry schedule-${entry.kind}`} key={entry.id}><div className="scheduleDateBlock"><strong>{day(entry.startsAt)}</strong><span>{time(entry.startsAt)}</span></div><span className="scheduleEntryRail"/><div className="scheduleEntryMain"><div className="row"><div className="timelineTitle">{entry.title}</div><span className="chip">{kindLabel[entry.kind]}</span></div>{entry.customerId&&<Link className="scheduleCustomer scheduleCustomerLink" href={`/people/${entry.customerId}`}>{customer?.displayName??"お客様"}さん <span>›</span></Link>}{entry.note&&<div className="formHint">{entry.note}</div>}</div></article>};
 return <main className="shell scheduleShell"><AppHeader title="予定" rightHref="#add-schedule" rightLabel="＋"/>
 <div className="scheduleIntro"><strong>{range.title}</strong><small>来店・誕生日・約束・イベントをまとめて確認できます。</small></div><div className="scheduleLegend"><span>来店</span><span>誕生日</span><span>約束</span><span>その他</span></div>
 <div className="filterRow scheduleViewTabs" aria-label="予定の表示切り替え"><Link className={`filterPill${view==="day"?" filterActive":""}`} href={scheduleHref("day",cursorDate)}>日</Link><Link className={`filterPill${view==="week"?" filterActive":""}`} href={scheduleHref("week",cursorDate)}>週</Link><Link className={`filterPill${view==="month"?" filterActive":""}`} href={scheduleHref("month",cursorDate)}>月</Link></div>
 <div className="schedulePager" aria-label="期間の移動"><Link className="secondaryButton actionLink" href={scheduleHref(view,range.prev)}>‹ 前へ</Link><Link className="secondaryButton actionLink" href={`/schedule?view=${view}`}>今日</Link><Link className="secondaryButton actionLink" href={scheduleHref(view,range.next)}>次へ ›</Link></div>
 {saved&&<div className="card successCard compactForm">✓ 予定を追加しました</div>}{error==="customer"&&<div className="formError">来店予定は、お客様を選んでください。</div>}{error==="datetime"&&<div className="formError">日時を選んでください。</div>}
 <div className="sectionHeading"><div><div className="sectionTitle">{viewLabel[view]}の予定</div></div><span className="scheduleCount">{visible.length}件</span></div>
 {view==="month"?<><div className="card scheduleMonth"><div className="scheduleMonthWeekdays">{["日","月","火","水","木","金","土"].map(label=><span key={label}>{label}</span>)}</div><div className="scheduleMonthGrid">{monthGrid.map(cell=>{const dayEntries=entriesForDay(sorted,cell.key);return <Link className={`scheduleMonthCell${cell.currentMonth?"":" monthMuted"}${cell.today?" monthToday":""}`} href={scheduleHref("day",cell.date)} key={cell.key}><strong>{cell.day}</strong><span>{dayEntries.slice(0,3).map(entry=><i className={`scheduleDot scheduleDot-${entry.kind}`} key={entry.id} title={kindLabel[entry.kind]}>{kindIcon[entry.kind]}</i>)}</span></Link>})}</div></div>{visible.length>0&&<div className="scheduleList scheduleMonthAgenda">{visible.slice(0,8).map(renderEntry)}</div>}</>:visible.length>0?<div className="scheduleList">{visible.map(renderEntry)}</div>:<div className="card empty scheduleEmpty"><span>♢</span><strong>{viewLabel[view]}の予定はありません</strong><small>右上の＋から、次に会う日や大切な予定を追加できます。</small></div>}
 <details className="detailsCard scheduleAddCard" id="add-schedule" open={sorted.length===0||Boolean(error)}><summary>＋ 予定を追加</summary><form action={createScheduleAction} className="stack scheduleForm detailsBody"><div className="scheduleFormLead"><strong>何の予定ですか？</strong><small>来店ならお客様も一緒に選べます。誕生日もここから登録できます。</small></div><div className="chips choiceRow">{(["visit","shift","birthday","unavailable","self_investment","other"] as const).map(kind=><label className="choiceChip" key={kind}><input type="radio" name="kind" value={kind} defaultChecked={kind==="visit"}/>{kindLabel[kind]}</label>)}</div>{customers.length>0&&<select className="selectBox" name="customerId" defaultValue=""><option value="">お客様を選ぶ（来店・誕生日の時）</option>{customers.map(customer=><option key={customer.customerId} value={customer.customerId}>{customer.displayName}</option>)}</select>}<label className="fieldLabel" htmlFor="startsAt">日時</label><input id="startsAt" className="searchBox scheduleDateTime" name="startsAt" type="datetime-local"/><input className="searchBox" name="title" placeholder="内容（空欄でもOK）" autoComplete="off"/><input className="searchBox" name="note" placeholder="その日に覚えておきたいこと" autoComplete="off"/><button className="primaryButton" type="submit">この予定を追加</button></form></details><BottomNav/></main>;
}
