import Link from "next/link";
import { notFound } from "next/navigation";
import { getCapture } from "@/lib/capture-repository";
import { getRequestIdentity } from "@/lib/auth/request-identity";
import { structureCapture } from "@/lib/ai-platform-core";
import { rememberGroups } from "@/lib/remember-fields";
import { confirmKnowledgeCandidatesAction } from "./actions";
const labels={knowledge:"新しく分かったこと",preference:"好み",next_topic:"次回話題",schedule:"予定",gift:"贈り物",unknown:"その他"};
function extractMemoryTags(value:string){const fields=new Map(rememberGroups.flatMap(group=>group.fields.map(field=>[field.label,{group:group.title,label:field.label}] as const)));const found:Array<{group:string;label:string;value:string;tag:string}>=[];for(const part of value.split(/[。\n]+/).map(v=>v.trim()).filter(Boolean)){const index=part.indexOf("：");if(index<1)continue;const label=part.slice(0,index).trim();const content=part.slice(index+1).trim();const field=fields.get(label);if(field&&content)found.push({...field,value:content,tag:`${label}：${content}`})}return Array.from(new Map(found.map(item=>[item.tag,item])).values())}
export default async function OrganizeCapturePage({params,searchParams}:{params:Promise<{captureId:string}>;searchParams:Promise<{fromVisit?:string}>}){const {captureId}=await params;const {fromVisit}=await searchParams;const {workspaceId,userId,ownerUserId}=await getRequestIdentity();const capture=await getCapture(captureId,workspaceId,userId);if(!capture)notFound();const structured=await structureCapture(capture.value,ownerUserId);const memoryTags=extractMemoryTags(capture.value);const exactTags=new Set(memoryTags.map(item=>item.tag));const candidates=structured.candidates.filter(candidate=>!exactTags.has(candidate.value));const knowledge=candidates.filter(c=>c.type==="knowledge"),preferences=candidates.filter(c=>c.type==="preference"),nextTopics=candidates.filter(c=>c.type==="next_topic"),schedules=candidates.filter(c=>c.type==="schedule"),gifts=candidates.filter(c=>c.type==="gift"),deferred=candidates.filter(c=>!["knowledge","preference","next_topic","schedule","gift"].includes(c.type));const candidateCount=memoryTags.length+candidates.length;const backParams=new URLSearchParams();if(capture.customerId)backParams.set("customerId",capture.customerId);if(fromVisit)backParams.set("fromVisit",fromVisit);const backHref=backParams.size?`/capture?${backParams.toString()}`:"/capture";
return <main className="shell"><header className="header"><Link className="subtle" href={backHref}>‹ 戻る</Link><span className="subtle">確認</span></header><section className="hero"><h1>{candidateCount?"覚える内容を確認":"会話を保存しました"}</h1><p>どこに残るかを確認できます。不要なものはチェックを外してください。</p></section><details className="detailsCard"><summary>入力した内容を見る</summary><div className="detailsBody timelineBody">{capture.value}</div></details>
<form action={confirmKnowledgeCandidatesAction.bind(null,capture.id,fromVisit)} className="stack compactForm">
{memoryTags.length>0&&<><div className="sectionTitle">この人について覚える</div><div className="formHint">スタンプで選んだ内容です。お客様の記憶として項目別に残ります。</div><div className="memoryReviewList">{memoryTags.map(item=><label className="card memoryReviewItem" key={item.tag}><input type="checkbox" name="memoryTag" value={item.tag} defaultChecked/><div><div className="formHint">{item.group} › {item.label}</div><strong>{item.value}</strong></div><span className="memoryDestination">人物情報</span></label>)}</div></>}
{knowledge.length>0&&<><div className="sectionTitle">会話から分かったこと</div><div className="formHint">人物情報として残します。</div><div className="chips reviewChips">{knowledge.map((candidate,index)=><label className="choiceChip reviewChoice" key={`${candidate.value}-${index}`}><input type="checkbox" name="knowledge" value={candidate.value} defaultChecked/><span>{candidate.value}</span></label>)}</div></>}
{preferences.length>0&&<><div className="sectionTitle">好みとして残す</div><div className="formHint">次回の接客前に確認できる好みに追加します。</div><div className="chips reviewChips">{preferences.map((candidate,index)=><label className="choiceChip reviewChoice" key={`${candidate.value}-${index}`}><input type="checkbox" name="preference" value={candidate.value} defaultChecked/><span>{candidate.value}</span></label>)}</div></>}
{nextTopics.length>0&&<><div className="sectionTitle">次に話したいこと</div><div className="formHint">次回の「次に話すこと」に残ります。最大3件を優先表示します。</div><div className="chips reviewChips">{nextTopics.map((candidate,index)=><label className="choiceChip reviewChoice" key={`${candidate.value}-${index}`}><input type="checkbox" name="nextTopic" value={candidate.value} defaultChecked/><span>{candidate.value}</span></label>)}</div></>}
{schedules.length>0&&<><div className="sectionTitle">予定に残す</div>{schedules.map((candidate,index)=><div className="reviewRow" key={`${candidate.value}-${index}`}><input type="hidden" name="scheduleValue" value={candidate.value}/><div className="reviewLabel">{candidate.value}</div><input className="compactDateInput" aria-label={`${candidate.value}の日時`} type="datetime-local" name="scheduleStartsAt"/></div>)}</>}
{gifts.length>0&&<><div className="sectionTitle">贈り物として残す</div><input type="hidden" name="giftCount" value={gifts.length}/>{gifts.map((candidate,index)=><div className="reviewRow reviewGiftRow" key={`${candidate.value}-${index}`}><input type="hidden" name={`giftValue-${index}`} value={candidate.value}/><div className="reviewLabel">{candidate.value}</div>{capture.customerId?<div className="miniChoices"><label className="choiceChip"><input type="radio" name={`giftDirection-${index}`} value="received"/><span>もらった</span></label><label className="choiceChip"><input type="radio" name={`giftDirection-${index}`} value="given"/><span>あげた</span></label><label className="choiceChip"><input type="radio" name={`giftDirection-${index}`} value="skip" defaultChecked/><span>登録しない</span></label></div>:null}</div>)}</>}
{deferred.length>0&&<details className="detailsCard"><summary>その他 {deferred.length}件</summary><div className="stack detailsBody">{deferred.map((candidate,index)=><div className="row" key={`${candidate.type}-${candidate.value}-${index}`}><span>{candidate.value}</span><span className="formHint">{labels[candidate.type]}</span></div>)}</div></details>}
<div className="stickyConfirm stack"><button className="primaryButton" type="submit" name="submitIntent" value="done">この内容で保存</button><button className="secondaryButton" type="submit" name="submitIntent" value="continue">続けて記録する</button></div></form></main>}
