import Link from "next/link";
import { BottomNav } from "@/components/bottom-nav";
import { CaptureChatInput } from "@/components/capture-chat-input";
import { getRequestIdentity } from "@/lib/auth/request-identity";
import { getGrowthCustomer,listGrowthCustomers } from "@/lib/growth-engine-customer";
import { getCustomerMemory } from "@/lib/customer-memory-repository";
import { visibleNextTopics } from "@/lib/next-topic";
import { rememberGroups } from "@/lib/remember-fields";
import { organizeCaptureAction } from "./organize/actions";
export default async function CapturePage({searchParams}:{searchParams:Promise<{customerId?:string;saved?:string;error?:string;fromVisit?:string}>}){const {customerId,saved,error,fromVisit}=await searchParams;const {workspaceId,userId}=await getRequestIdentity();if(!customerId){const customers=await listGrowthCustomers(workspaceId,userId);return <main className="shell"><header className="header"><Link className="subtle" href="/add">‹ 追加</Link><div className="brand">今日の接客</div></header><section className="hero"><h1>誰との話を残しますか？</h1><p>お客様を選ぶと、前回を確認してすぐ記録できます。</p></section><div className="stack">{customers.map(c=>{const name=c.displayName??"お客様";return <Link className="card personRow" href={`/capture?customerId=${encodeURIComponent(c.customerId)}`} key={c.customerId}><div className="avatar">{name.slice(0,1)}</div><div className="personMain"><div className="personName">{name}</div></div><span>›</span></Link>})}{customers.length===0&&<div className="card empty">登録済みのお客様がいません</div>}</div><BottomNav/></main>}
 const [customer,memory]=await Promise.all([getGrowthCustomer(workspaceId,userId,customerId),getCustomerMemory(workspaceId,userId,customerId)]);const displayName=customer?.displayName??"お客様";const nextTopics=visibleNextTopics(memory?.nextTopicHint,3);const recall=[memory?.cautionNote&&{label:"注意",value:memory.cautionNote},memory?.lastInteractionSummary&&{label:"前回",value:memory.lastInteractionSummary},memory?.preferenceNote&&{label:"好み",value:memory.preferenceNote}].filter(Boolean) as Array<{label:string;value:string}>;const phase: "first"|"repeat"=((memory?.tags?.length??0)===0&&!memory?.lastInteractionSummary)?"first":"repeat";
 return <main className="shell"><header className="header"><Link className="subtle" href="/capture">‹ お客様を選ぶ</Link><span className="subtle">{displayName}</span></header><section className="hero"><h1>{phase==="first"?"この人を覚える":fromVisit?"今日、何を話しましたか？":"今日の接客を残す"}</h1><p>{phase==="first"?"最初は人物像を広く。スタンプ・文章・音声を自由に組み合わせられます。":"今日の変化や会話を中心に、気づいたことを残します。"}</p></section>{(recall.length>0||nextTopics.length>0)&&<details className="detailsCard" open={!fromVisit}><summary>前回を確認</summary><div className="stack detailsBody">{recall.map(item=><div key={item.label}><div className="formHint">{item.label}</div><div className="timelineBody">{item.value}</div></div>)}{nextTopics.length>0&&<div><div className="formHint">次に話すこと</div>{nextTopics.map(topic=><div className="timelineBody" key={topic}>・{topic}</div>)}</div>}</div></details>}{saved&&<div className="card successCard"><div className="formHint">登録した内容</div><strong>{saved}</strong></div>}{error&&<div className="formError">入力内容を確認してください。</div>}<div className="sectionTitle">チャット入力</div><form action={organizeCaptureAction.bind(null,customerId,fromVisit)} className="stack"><CaptureChatInput groups={rememberGroups} knownTags={memory?.tags??[]} phase={phase} placeholder={phase==="first"?"見た目、仕事、趣味、好みなど。分かったことをそのまま入力。":"今日話したことや変わったことをそのまま入力。"}/><button className="primaryButton" type="submit">整理して確認</button></form><div className="sectionTitle">項目から入力</div><Link className="secondaryButton actionLink" href={`/remember?customerId=${encodeURIComponent(customerId)}`}>登録項目の一覧を開く</Link><BottomNav/></main>}
