import Link from "next/link";
import { BottomNav } from "@/components/bottom-nav";
import { getGrowthEngineBridgeStatus } from "@/lib/growth-engine-customer";
import { createCustomerFromVelvetAction } from "./actions";
const profileGroups=[{title:"見た目",items:["髪","メガネ","顔の特徴"]},{title:"服装・持ち物",items:["服装","時計","財布","アクセサリー"]},{title:"人となり",items:["仕事","結婚","出身","趣味","人柄","家族"]},{title:"好み",items:["よく飲むもの","好きなもの","苦手なもの"]},{title:"接客で覚えること",items:["着席理由","注意点"]}];
export default async function AddPage({searchParams}:{searchParams:Promise<{error?:string;name?:string}>}){const {error,name}=await searchParams;const bridge=getGrowthEngineBridgeStatus();return <main className="shell"><header className="header"><div className="brand">追加</div></header><section className="hero"><h1>何を残しますか？</h1><p>初めて会った人と、いつものお客様で入口を分けています。</p></section>
 <div className="card"><div className="timelineTitle">初めてのお客様</div><div className="timelineBody">まず名前だけ登録します。外見や好みは次の画面で、分かったところだけ残せます。</div>{bridge.configured?<form action={createCustomerFromVelvetAction} className="stack compactForm"><input className="searchBox" name="displayName" placeholder="名前・呼び名" defaultValue={name??""} autoComplete="off"/>{error==="name"&&<div className="formError">名前か呼び名を入れてください。</div>}{error==="customer_create"&&<div className="formError">今はお客様を登録できません。少し時間をおいて再度お試しください。</div>}<button className="primaryButton" type="submit">名前を登録して、この人を覚える</button></form>:<><div className="card noticeCard"><div className="timelineTitle">新しいお客様の登録は準備中です</div><div className="formHint">登録機能の接続が終わるまで、下から登録項目を確認できます。</div></div><details className="detailsCard"><summary>登録できる項目を見る</summary><div className="stack detailsBody">{profileGroups.map(group=><div key={group.title}><div className="fieldLabel">{group.title}</div><div className="chips">{group.items.map(item=><span className="chip" key={item}>{item}</span>)}</div></div>)}</div></details></>}</div>
 <div className="sectionTitle">登録済みのお客様</div><div className="stack registerHub"><Link className="card registerChoice" href="/capture"><div className="registerIcon">話</div><div><strong>今日の接客を残す</strong><p>前回を確認して、今日話したことを記録</p></div><span>›</span></Link><Link className="card registerChoice" href="/remember"><div className="registerIcon">人</div><div><strong>この人について追加</strong><p>見た目・持ち物・人となり・好みなど</p></div><span>›</span></Link></div>
 <div className="sectionTitle">その他</div><div className="stack registerHub"><Link className="card registerChoice" href="/schedule"><div className="registerIcon">予</div><div><strong>予定を追加</strong><p>来店・出勤・誕生日・自分の予定など</p></div><span>›</span></Link><Link className="card registerChoice" href="/self-investment"><div className="registerIcon">自</div><div><strong>自分の記録</strong><p>美容・衣装・学びなど、自分のための記録</p></div><span>›</span></Link></div><BottomNav/></main>}
