import Link from "next/link";
import { BottomNav } from "@/components/bottom-nav";
import { getGrowthEngineBridgeStatus,listGrowthCustomers } from "@/lib/growth-engine-customer";
import { rememberPreviewGroups } from "@/lib/remember-fields";
import { getRequestIdentity } from "@/lib/auth/request-identity";
import { getPlanAccess } from "@/lib/plan-access";
import { createCustomerFromVelvetAction } from "./actions";
export default async function AddPage({searchParams}:{searchParams:Promise<{error?:string;name?:string;count?:string}>}){const {error,name}=await searchParams;const bridge=getGrowthEngineBridgeStatus();const {workspaceId,userId,ownerUserId}=await getRequestIdentity();const [access,customers]=await Promise.all([getPlanAccess(ownerUserId),bridge.configured?listGrowthCustomers(workspaceId,userId):Promise.resolve([])]);const atLimit=Boolean(access.customerLimit&&customers.length>=access.customerLimit);return <main className="shell"><header className="header"><div className="brand">追加</div><Link className="subtle" href="/plans">{access.plan==="free"?`${customers.length}/30`:access.plan==="pro"?"Pro":"Business"}</Link></header>
 <div className="card"><div className="timelineTitle">初めてのお客様</div>{bridge.configured?<form action={createCustomerFromVelvetAction} className="stack compactForm"><input className="searchBox" name="displayName" placeholder="名前・呼び名" defaultValue={name??""} autoComplete="off" disabled={atLimit}/>{error==="name"&&<div className="formError">名前か呼び名を入れてください。</div>}{error==="customer_create"&&<div className="formError">今はお客様を登録できません。少し時間をおいて再度お試しください。</div>}{(error==="customer_limit"||atLimit)&&<div className="card noticeCard"><strong>Freeは30名までです</strong><div className="formHint">登録済み {customers.length}/30名。Proでは人数の上限なく管理できます。</div><Link className="secondaryButton actionLink" href="/plans">プランを見る</Link></div>}<button className="primaryButton" type="submit" disabled={atLimit}>名前を登録して、この人を覚える</button></form>:<><div className="card noticeCard"><div className="timelineTitle">新しいお客様の登録は準備中です</div><div className="formHint">登録機能の接続が終わるまで、下から登録項目を確認できます。</div></div><details className="detailsCard" open><summary>登録できる項目を見る</summary><div className="stack detailsBody">{rememberPreviewGroups.map(group=><div key={group.title}><div className="fieldLabel">{group.title}</div><div className="chips">{group.labels.map(item=><span className="chip" key={item}>{item}</span>)}</div></div>)}</div></details></>}</div>
 <div className="sectionTitle">登録済みのお客様</div><div className="stack registerHub"><Link className="card registerChoice" href="/capture"><div className="registerIcon">話</div><div><strong>今日の接客を残す</strong><p>前回を確認して、今日話したことを記録</p></div><span>›</span></Link><Link className="card registerChoice" href="/remember"><div className="registerIcon">人</div><div><strong>この人について追加</strong><p>見た目・仕事・趣味・好み・接客の好みなど</p></div><span>›</span></Link></div>
 <div className="sectionTitle">その他</div><div className="stack registerHub"><Link className="card registerChoice" href="/schedule"><div className="registerIcon">予</div><div><strong>予定を追加</strong><p>来店・出勤・誕生日・自分の予定など</p></div><span>›</span></Link><Link className="card registerChoice" href="/self-investment"><div className="registerIcon">自</div><div><strong>自分の記録</strong><p>美容・衣装・学びなど、自分のための記録</p></div><span>›</span></Link></div><BottomNav/></main>}
