"use client";

import Link from "next/link";
import { useMemo,useRef,useState } from "react";
import type { RememberGroup, RememberSection } from "@/lib/remember-fields";
import { INPUT_LIMITS } from "@/lib/input-limits";
type StructuredRememberItem={sectionId:string;topicId:string;label:string;content:string};
type SpeechRecognitionLike={lang:string;interimResults:boolean;continuous:boolean;start:()=>void;stop:()=>void;onresult:((event:{results:ArrayLike<{0:{transcript:string};isFinal?:boolean}>})=>void)|null;onerror:(()=>void)|null;onend:(()=>void)|null};type SpeechRecognitionConstructor=new()=>SpeechRecognitionLike;type Stamp={label:string;content:string};declare global{interface Window{SpeechRecognition?:SpeechRecognitionConstructor;webkitSpeechRecognition?:SpeechRecognitionConstructor}}
const stampKey=(stamp:Stamp)=>`${stamp.label}::${stamp.content}`;
const fallbackSection=(groups:RememberGroup[],phase:"first"|"repeat"):RememberSection=>({id:phase==="first"?"profile":"conversation",title:phase==="first"?"人物情報":"今日の会話",shortTitle:phase==="first"?"人物情報":"今日の会話",hint:phase==="first"?"見た目・仕事・趣味・好みなど":"前回の続きや今日話したこと",groups});
export function CaptureChatInput({groups,sections,knownTags=[],phase="repeat",name="value",placeholder,voiceAllowed=false}:{groups:RememberGroup[];sections?:RememberSection[];knownTags?:string[];phase?:"first"|"repeat";name?:string;placeholder:string;voiceAllowed?:boolean}){
 const availableSections=sections?.length?sections:[fallbackSection(groups,phase)];
 const [value,setValue]=useState("");const [structured,setStructured]=useState<StructuredRememberItem[]>([]);const [fieldSearch,setFieldSearch]=useState("");const [nextActionOptionsOpen,setNextActionOptionsOpen]=useState(false);const [recording,setRecording]=useState(false);const [unsupported,setUnsupported]=useState(false);const [limitReached,setLimitReached]=useState(false);const [stampOpen,setStampOpen]=useState(false);const [sectionIndex,setSectionIndex]=useState(0);const [groupIndex,setGroupIndex]=useState(0);const [drafts,setDrafts]=useState<Record<string,string>>({});const [justAdded,setJustAdded]=useState("");const recognitionRef=useRef<SpeechRecognitionLike|null>(null);const feedbackTimer=useRef<ReturnType<typeof setTimeout>|null>(null);
 const section=availableSections[sectionIndex]??availableSections[0];const group=section?.groups[groupIndex]??section?.groups[0];const visibleFields=useMemo(()=>{const q=fieldSearch.trim().toLowerCase();if(!q)return group?.fields??[];return (section?.groups.flatMap(g=>g.fields)??[]).filter(f=>[f.label,f.topicId,...f.examples].some(v=>v.toLowerCase().includes(q)))},[fieldSearch,group,section]);const knownByLabel=useMemo(()=>{const map=new Map<string,string>();for(const tag of knownTags){const index=tag.indexOf("：");if(index>0)map.set(tag.slice(0,index),tag.slice(index+1))}return map},[knownTags]);
 function structuredItem(label:string,content:string):StructuredRememberItem|undefined{const field=section?.groups.flatMap(item=>item.fields).find(item=>item.label===label);return field?{sectionId:section.id,topicId:field.topicId,label,content}:undefined}
 function append(text:string){setValue(current=>{const trimmed=current.trimEnd();const next=trimmed?`${trimmed}${/[。\\n]$/.test(trimmed)?"":"。"}${text}`:text;if(next.length>INPUT_LIMITS.capture){setLimitReached(true);return current}setLimitReached(false);return next})}function feedback(stamp:Stamp){setJustAdded(`${stamp.label}：${stamp.content}`);if(feedbackTimer.current)clearTimeout(feedbackTimer.current);feedbackTimer.current=setTimeout(()=>setJustAdded(""),700)}function addStamp(label:string,content:string){const stamp={label,content};append(`${label}：${content}`);const item=structuredItem(label,content);if(item){setStructured(current=>[...current,item]);if(item.sectionId==="next_action"&&!item.topicId.startsWith("action.meta."))setNextActionOptionsOpen(true)}feedback(stamp)}function addDraft(label:string){const content=(drafts[label]??"").trim();if(!content)return;addStamp(label,content);setDrafts(current=>({...current,[label]:""}))}
 function startRecording(){if(!voiceAllowed)return;const Recognition=window.SpeechRecognition??window.webkitSpeechRecognition;if(!Recognition){setUnsupported(true);return}const recognition=new Recognition();recognition.lang="ja-JP";recognition.interimResults=false;recognition.continuous=false;recognition.onresult=event=>{const transcript=Array.from(event.results).map(result=>result[0]?.transcript??"").join("").trim();if(transcript)append(transcript)};recognition.onerror=()=>setRecording(false);recognition.onend=()=>{setRecording(false);recognitionRef.current=null};recognitionRef.current=recognition;setUnsupported(false);setRecording(true);recognition.start()}function stopRecording(){recognitionRef.current?.stop();setRecording(false)}
 function StampChoices({stamps}:{stamps:Stamp[]}){return <div className="stampChoiceRow">{stamps.map(stamp=>{const known=knownByLabel.get(stamp.label)===stamp.content;return <button type="button" className={`chip chipButton stampChoice ${known?"knownStamp":""} ${justAdded===`${stamp.label}：${stamp.content}`?"stampAdded":""}`} key={stampKey(stamp)} onClick={()=>addStamp(stamp.label,stamp.content)}>{stamp.content}{known&&<span className="knownDot">●</span>}</button>})}</div>}
 return <div className="chatComposer"><input type="hidden" name="structuredRemember" value={JSON.stringify(structured)}/><div className="chatInputWrap"><textarea className="searchBox captureTextArea chatTextArea" name={name} value={value} onChange={event=>{setValue(event.target.value);setLimitReached(false)}} placeholder={placeholder} autoComplete="off" rows={4} maxLength={INPUT_LIMITS.capture}/><div className="chatTools"><button className={`composerTool ${stampOpen?"activeAction":""}`} type="button" onClick={()=>setStampOpen(open=>!open)} aria-expanded={stampOpen}><span>▦</span>分類</button>{voiceAllowed?<button className={`composerTool ${recording?"recording":""}`} type="button" onClick={recording?stopRecording:startRecording}><span>{recording?"■":"●"}</span>{recording?"停止":"音声"}</button>:<Link className="composerTool" href="/plans" aria-label="Proで音声入力を使う"><span>🔒</span>音声</Link>}</div></div>
 {nextActionOptionsOpen&&section?.id==="next_action"&&<div className="card noticeCard"><div className="row"><strong>必要なら追加</strong><button type="button" className="subtle compactButton" onClick={()=>setNextActionOptionsOpen(false)}>閉じる</button></div><div className="stampChoiceRow"><button type="button" className="chip chipButton stampChoice" onClick={()=>addStamp("次回来店時","次回来店時")}>次回来店時</button><button type="button" className="chip chipButton stampChoice" onClick={()=>addStamp("優先度","高")}>優先度 高</button></div><div className="profileInputRow stampFreeInput"><input className="searchBox" type="date" aria-label="期限" onChange={event=>{if(event.target.value)addStamp("日付",event.target.value)}}/></div></div>}{stampOpen&&<section className="stampPanel"><div className="stampSectionChoices" aria-label="覚える入口">{availableSections.map((item,index)=><button type="button" className={`stampSectionCard ${sectionIndex===index?"selectedChip":""}`} key={item.id} onClick={()=>{setSectionIndex(index);setGroupIndex(0)}}><strong>{item.title}</strong><span>{item.hint}</span></button>)}</div><div className="stampTabs" role="tablist" aria-label={`${section?.title??"分類"}の分類`}>{section?.groups.map((item,index)=>{const knownCount=item.fields.filter(f=>knownByLabel.has(f.label)).length;return <button type="button" className={`stampTab ${groupIndex===index?"selectedChip":""}`} key={item.title} onClick={()=>setGroupIndex(index)}>{item.title}{knownCount>0&&<small>{knownCount}</small>}</button>})}</div><input className="searchBox" type="search" value={fieldSearch} onChange={event=>setFieldSearch(event.target.value)} placeholder="項目・候補を検索"/><div className="stampFieldList">{visibleFields.map(field=>{const known=knownByLabel.get(field.label);return <div className="stampFieldCard" key={`${field.topicId}-${field.label}`}><div className="row stampFieldHeader"><strong>{field.label}</strong>{known&&<span className="knownValue">登録済み：{known}</span>}</div>{field.examples.length>0?<StampChoices stamps={field.examples.map(content=>({label:field.label,content}))}/>:<div className="stampEmpty">候補がない項目です。下の自由入力から追加できます。</div>}<div className="profileInputRow stampFreeInput"><input className="searchBox" value={drafts[field.label]??""} onChange={event=>setDrafts(current=>({...current,[field.label]:event.target.value}))} placeholder="短く入力"/><button className="secondaryButton compactButton" type="button" onClick={()=>addDraft(field.label)}>追加</button></div></div>})}</div></section>}
 <div className="formHint">{limitReached?`一度に覚えられるのは${INPUT_LIMITS.capture.toLocaleString("ja-JP")}文字までです。`:recording?"聞き取っています。止めるとチャット欄に追加します。":unsupported?"この端末では音声入力を利用できません。文字と分類入力は使えます。":voiceAllowed?"全部埋めなくて大丈夫。文字・音声・分類入力を自由に組み合わせられます。":"文字と分類入力で覚えられます。音声入力はProで使えます。"}</div></div>
}
