import Link from "next/link";
import { BottomNav } from "@/components/bottom-nav";
import { getRequestIdentity } from "@/lib/auth/request-identity";
import { getCustomerMemory } from "@/lib/customer-memory-repository";
import { getGrowthCustomerDisplay } from "@/lib/growth-engine-customer";
import { getActiveProfessionalVisit } from "@/lib/professional-visit-repository";
import { listProfessionalTimeline,type ProfessionalTimelineItem } from "@/lib/professional-timeline-repository";
import { buildCustomerRecall } from "@/lib/customer-recall";
import { rememberGroups } from "@/lib/remember-fields";
import { startVisitAction } from "@/app/visits/actions";
import { toggleCustomerPinAction } from "./actions";
const eventLabels:Record<string,string>={visit:"来店",conversation:"会話",note:"メモ",gift:"贈り物",schedule:"予定",relationship:"関係"};function tagLabel(value:string){const index=value.indexOf("：");return index>=0?value.slice(0,index):""}function TimelineRows({items}:{items:ProfessionalTimelineItem[]}){return <div className="timeline">{items.map(item=><details className="timelineItem" key={item.id}><summary><span className="timelineDate">{item.occurredAt.slice(0,10)}{eventLabels[item.eventType]?` · ${eventLabels[item.eventType]}`:""}</span><span className="timelineTitle">{item.title}</span></summary>{item.body&&<div className="timelineBody">{item.body}</div>}</details>)}</div>}
export default async function CustomerDetailPage({params,searchParams}:{params:Promise<{customerId:string}>;searchParams:Promise<{justEnded?:string;captureSaved?:string;knowledgeAdded?:string;preferenceAdded?:string;nextTopicAdded?:string;scheduleAdded?:string;giftAdded?:string;memoryAdded?:string}>}){const {customerId}=await params;const query=await searchParams;const identity=await getRequestIdentity();const [customer,memory,timeline,activeVisit]=await Promise.all([getGrowthCustomerDisplay({workspaceId:identity.workspaceId,userId:identity.userId,customerId}),getCustomerMemory(identity.workspaceId,identity.userId,customerId),listProfessionalTimeline(identity.workspaceId,identity.userId,customerId),getActiveProfessionalVisit(identity.workspaceId,identity.userId,customerId)]);const displayName=customer.displayName||memory?.displayNameSnapshot||"お客様";const quickRecall=buildCustomerRecall(memory,{maxItems:4,maxNextTopics:2});const tags=memory?.tags??[];const grouped=rememberGroups.map(group=>({title:group.title,hint:group.hint,values:tags.filter(tag=>group.fields.some(field=>field.label===tagLabel(tag)))})).filter(group=>group.values.length>0);const knownLabels=new Set(tags.map(tagLabel).filter(Boolean));const totalFields=rememberGroups.reduce((sum,group)=>sum+group.fields.length,0);const recentTimeline=timeline.slice(0,8),olderTimeline=timeline.slice(8);const savedItems=[Number(query.memoryAdded)>0&&`人物情報 ${query.memoryAdded}件`,Number(query.knowledgeAdded)>0&&`新しく分かったこと ${query.knowledgeAdded}件`,Number(query.preferenceAdded)>0&&`好み ${query.preferenceAdded}件`,Number(query.nextTopicAdded)>0&&`次回話題 ${query.nextTopicAdded}件`,Number(query.scheduleAdded)>0&&`予定 ${query.scheduleAdded}件`,Number(query.giftAdded)>0&&`贈り物 ${query.giftAdded}件`].filter(Boolean) as string[];
return <main className="shell customerDetailShell"><header className="header"><Link className="subtle" href="/people">‹ お客様</Link><div className="searchActions"><form action={toggleCustomerPinAction.bind(null,customerId)}><button className="subtle" type="submit">{memory?.pinned?"★":"☆"}</button></form><Link className="subtle" href={`/remember?customerId=${encodeURIComponent(customerId)}`}>情報を編集</Link></div></header><section className="hero customerHero"><h1>{displayName}</h1>{knownLabels.size>0?<p>{knownLabels.size}項目の情報を記録しています。</p>:<p>まだ人物情報はありません。</p>}</section><div className="customerPrimaryActions"><Link className="primaryButton actionLink" href={`/capture?customerId=${encodeURIComponent(customerId)}`}>今日の接客を残す</Link><Link className="secondaryButton actionLink" href={`/remember?customerId=${encodeURIComponent(customerId)}`}>情報を追加</Link></div>{query.captureSaved&&<div className="card successCard stack"><strong>今日の接客を記録しました</strong>{savedItems.map(item=><div className="timelineBody" key={item}>✓ {item}</div>)}</div>}{(quickRecall.items.length>0||quickRecall.nextTopics.length>0)&&<section className="card noticeCard"><div className="timelineTitle">10秒で思い出す</div><div className="quickRecallGrid">{quickRecall.items.map(item=><div key={`${item.label}-${item.value}`}><div className="formHint">{item.label}</div><div className="timelineBody">{item.value}</div></div>)}{quickRecall.nextTopics.length>0&&<div><div className="formHint">次に話すこと</div>{quickRecall.nextTopics.map(topic=><div className="timelineBody" key={topic}>・{topic}</div>)}</div>}</div></section>}{query.justEnded&&!activeVisit&&<Link className="card actionLink noticeCard" href={`/capture?customerId=${customerId}&fromVisit=${encodeURIComponent(query.justEnded)}`}><div className="timelineTitle">今日の接客を残す</div></Link>}
<div className="sectionTitle customerSectionTitle"><span>情報一覧</span><Link className="subtle" href={`/remember?customerId=${encodeURIComponent(customerId)}`}>追加・訂正 ›</Link></div>{grouped.length>0?<div className="stack memorySummaryGroups">{grouped.map(group=><section className="card memorySummaryGroup" key={group.title}><div className="row"><div><div className="timelineTitle">{group.title}</div>{group.hint&&<div className="formHint">{group.hint}</div>}</div><span className="subtle">{group.values.length}件</span></div><div className="memoryValueList">{group.values.map(value=>{const i=value.indexOf("：");return <div className="memoryValueRow" key={value}><span>{i>0?value.slice(0,i):"情報"}</span><strong>{i>0?value.slice(i+1):value}</strong></div>})}</div></section>)}</div>:<div className="card empty"><div>人物情報はまだありません</div><Link className="secondaryButton actionLink compactForm" href={`/remember?customerId=${encodeURIComponent(customerId)}`}>この人について追加</Link></div>}
<div className="sectionTitle customerSectionTitle"><span>履歴</span><span className="subtle">{timeline.length}件</span></div>{recentTimeline.length>0?<><TimelineRows items={recentTimeline}/>{olderTimeline.length>0&&<details className="detailsCard"><summary>以前の履歴を見る（{olderTimeline.length}件）</summary><div className="detailsBody"><TimelineRows items={olderTimeline}/></div></details>}</>:<div className="card empty">履歴はまだありません</div>}
<div className="sectionTitle">その他</div><div className="actions"><Link className="action actionLink" href={`/people/${customerId}/message`}>連絡文案</Link><Link className="action actionLink" href={`/people/${customerId}/gift`}>贈り物</Link><Link className="action actionLink" href={`/relationships/new?customerId=${customerId}`}>関係</Link></div>{activeVisit?<Link className="secondaryButton actionLink compactForm" href={`/visits/${activeVisit.id}`}>接客中を見る</Link>:<form action={startVisitAction} className="compactForm"><input type="hidden" name="customerId" value={customerId}/><button className="secondaryButton" type="submit">来店を記録</button></form>}{customer.contacts&&customer.contacts.length>0&&<details className="detailsCard"><summary>連絡先</summary><div className="chips detailsBody">{customer.contacts.map((contact,index)=><span className="chip" key={`${contact.type}-${index}`}>{contact.label||contact.type} · {contact.value}</span>)}</div></details>}<BottomNav/></main>}
