import { getStorageMode } from "@/lib/storage/config";
import { dbQuery } from "@/lib/storage/postgres";
import { getD1Database, makeD1Id } from "@/lib/storage/d1";
import type { ConversationEpisode } from "@/lib/conversation-episode-repository";

export type OngoingTopic={id:string;workspaceId:string;userId:string;customerId:string;topicId:string;label:string;latestContent:string;state:ConversationEpisode["state"];firstEpisodeId:string;latestEpisodeId:string;firstSeenAt:string;lastSeenAt:string;completedAt?:string;createdAt:string;updatedAt:string};
type Row={id:string;workspace_id:string;user_id:string;customer_id:string;topic_id:string;label:string;latest_content:string;state:ConversationEpisode["state"];first_episode_id:string;latest_episode_id:string;first_seen_at:string;last_seen_at:string;completed_at:string|null;created_at:string;updated_at:string};
const rows:OngoingTopic[]=[];const map=(r:Row):OngoingTopic=>({id:r.id,workspaceId:r.workspace_id,userId:r.user_id,customerId:r.customer_id,topicId:r.topic_id,label:r.label,latestContent:r.latest_content,state:r.state,firstEpisodeId:r.first_episode_id,latestEpisodeId:r.latest_episode_id,firstSeenAt:new Date(r.first_seen_at).toISOString(),lastSeenAt:new Date(r.last_seen_at).toISOString(),completedAt:r.completed_at?new Date(r.completed_at).toISOString():undefined,createdAt:new Date(r.created_at).toISOString(),updatedAt:new Date(r.updated_at).toISOString()});

export async function upsertOngoingTopicFromEpisode(e:ConversationEpisode){
 const now=new Date().toISOString(),completed=e.state==="done"?e.occurredAt:null,db=await getD1Database(),mode=getStorageMode();
 if(db){const existing=await db.prepare("select id,first_episode_id,first_seen_at,created_at from velvet_ongoing_topics where workspace_id=? and user_id=? and customer_id=? and topic_id=? limit 1").bind(e.workspaceId,e.userId,e.customerId,e.topicId).first<{id:string;first_episode_id:string;first_seen_at:string;created_at:string}>();const id=existing?.id??makeD1Id("topic");await db.prepare(`INSERT INTO velvet_ongoing_topics(id,workspace_id,user_id,customer_id,topic_id,label,latest_content,state,first_episode_id,latest_episode_id,first_seen_at,last_seen_at,completed_at,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(workspace_id,user_id,customer_id,topic_id) DO UPDATE SET label=excluded.label,latest_content=excluded.latest_content,state=excluded.state,latest_episode_id=excluded.latest_episode_id,last_seen_at=excluded.last_seen_at,completed_at=excluded.completed_at,updated_at=excluded.updated_at`).bind(id,e.workspaceId,e.userId,e.customerId,e.topicId,e.label,e.content,e.state,existing?.first_episode_id??e.id,e.id,existing?.first_seen_at??e.occurredAt,e.occurredAt,completed,existing?.created_at??now,now).run();return}
 if(mode!=="postgres"){const old=rows.find(x=>x.workspaceId===e.workspaceId&&x.userId===e.userId&&x.customerId===e.customerId&&x.topicId===e.topicId);if(old){Object.assign(old,{label:e.label,latestContent:e.content,state:e.state,latestEpisodeId:e.id,lastSeenAt:e.occurredAt,completedAt:completed??undefined,updatedAt:now})}else rows.unshift({id:`topic_${Date.now().toString(36)}`,workspaceId:e.workspaceId,userId:e.userId,customerId:e.customerId,topicId:e.topicId,label:e.label,latestContent:e.content,state:e.state,firstEpisodeId:e.id,latestEpisodeId:e.id,firstSeenAt:e.occurredAt,lastSeenAt:e.occurredAt,completedAt:completed??undefined,createdAt:now,updatedAt:now});return}
 await dbQuery(`insert into velvet_ongoing_topics(id,workspace_id,user_id,customer_id,topic_id,label,latest_content,state,first_episode_id,latest_episode_id,first_seen_at,last_seen_at,completed_at,created_at,updated_at) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$9,$10,$10,$11,$12,$12) on conflict(workspace_id,user_id,customer_id,topic_id) do update set label=excluded.label,latest_content=excluded.latest_content,state=excluded.state,latest_episode_id=excluded.latest_episode_id,last_seen_at=excluded.last_seen_at,completed_at=excluded.completed_at,updated_at=excluded.updated_at`,[`topic_${Date.now().toString(36)}_${Math.random().toString(36).slice(2,8)}`,e.workspaceId,e.userId,e.customerId,e.topicId,e.label,e.content,e.state,e.id,e.occurredAt,completed,now]);
}

export async function listOngoingTopics(workspaceId:string,userId:string,customerId:string,includeDone=false){
 const db=await getD1Database(),mode=getStorageMode();if(db){const q=`select * from velvet_ongoing_topics where workspace_id=? and user_id=? and customer_id=? ${includeDone?"":"and state<>'done'"} order by last_seen_at desc`;const r=await db.prepare(q).bind(workspaceId,userId,customerId).all<Row>();return r.results.map(map)}if(mode!=="postgres")return rows.filter(x=>x.workspaceId===workspaceId&&x.userId===userId&&x.customerId===customerId&&(includeDone||x.state!=="done")).sort((a,b)=>b.lastSeenAt.localeCompare(a.lastSeenAt));const r=await dbQuery<Row>(`select id,workspace_id,user_id,customer_id,topic_id,label,latest_content,state,first_episode_id,latest_episode_id,first_seen_at::text,last_seen_at::text,completed_at::text,created_at::text,updated_at::text from velvet_ongoing_topics where workspace_id=$1 and user_id=$2 and customer_id=$3 ${includeDone?"":"and state<>'done'"} order by last_seen_at desc`,[workspaceId,userId,customerId]);return r.rows.map(map)}
