import { getPlanAccess, isWithinHistoryWindow } from "@/lib/plan-access";
import { getStorageMode } from "@/lib/storage/config";
import { dbQuery } from "@/lib/storage/postgres";

export type VisitContext = "solo" | "group" | "entertainment" | "business" | "accompaniment" | "other";
export type NominationType = "main" | "in_store" | "help" | "free" | "other";
export type ReceivableStatus = "open" | "partial" | "paid";
export type Visit = {
  id:string; ownerUserId:string; participantIds:string[]; startedAt:string; endedAt?:string; durationMinutes?:number;
  salesAmount?:number; paymentMethod?:"cash"|"card"|"qr"|"receivable"|"other"; seatingReason?:string; visitContext?:VisitContext;
  nominationType?:NominationType; receivableAmount?:number; receivableStatus?:ReceivableStatus; drinkCount?:number; bottleCount?:number; bottleNote?:string;
};
export type PersonVisitStats = { visitCount:number; totalSales:number; averageStayMinutes?:number; lastVisitAt?:string; commonPaymentMethod?:Visit["paymentMethod"]; mainNominationCount:number; inStoreNominationCount:number; openReceivableAmount:number; drinkCount:number; bottleCount:number };
type ReadOptions={includeArchived?:boolean};
const visits:Visit[]=[];
type VisitRow={id:string;owner_user_id:string;started_at:string;ended_at:string|null;duration_minutes:number|null;sales_amount:number|null;payment_method:Visit["paymentMethod"]|null;seating_reason:string|null;visit_context:VisitContext|null;nomination_type:NominationType|null;receivable_amount:number|null;receivable_status:ReceivableStatus|null;drink_count:number|null;bottle_count:number|null;bottle_note:string|null};
type ParticipantRow={visit_id:string;person_id:string};
function mapVisit(row:VisitRow,participantIds:string[]):Visit{return{id:row.id,ownerUserId:row.owner_user_id,participantIds,startedAt:new Date(row.started_at).toISOString(),endedAt:row.ended_at?new Date(row.ended_at).toISOString():undefined,durationMinutes:row.duration_minutes??undefined,salesAmount:row.sales_amount??undefined,paymentMethod:row.payment_method??undefined,seatingReason:row.seating_reason??undefined,visitContext:row.visit_context??undefined,nominationType:row.nomination_type??undefined,receivableAmount:row.receivable_amount??undefined,receivableStatus:row.receivable_status??undefined,drinkCount:row.drink_count??undefined,bottleCount:row.bottle_count??undefined,bottleNote:row.bottle_note??undefined};}
const visitSelect="id,owner_user_id,started_at::text,ended_at::text,duration_minutes,sales_amount,payment_method,seating_reason,visit_context,nomination_type,receivable_amount,receivable_status,drink_count,bottle_count,bottle_note";

/** Legacy migration/rollback reader only. No product code may write this store. */
export async function listVisits(ownerUserId:string,options:ReadOptions={}):Promise<Visit[]>{const access=await getPlanAccess(ownerUserId);if(getStorageMode()!=="postgres")return visits.filter(v=>v.ownerUserId===ownerUserId&&(options.includeArchived||isWithinHistoryWindow(v.startedAt,access)));const cutoff=options.includeArchived||access.fullHistory?null:access.historyCutoff?.toISOString()??null;const[visitRows,participantRows]=await Promise.all([dbQuery<VisitRow>(`select ${visitSelect} from velvet_visits where owner_user_id=$1 and ($2::timestamptz is null or started_at >= $2) order by started_at desc`,[ownerUserId,cutoff]),dbQuery<ParticipantRow>(`select vp.visit_id,vp.person_id from velvet_visit_participants vp join velvet_visits v on v.id=vp.visit_id and v.owner_user_id=vp.owner_user_id where vp.owner_user_id=$1 and ($2::timestamptz is null or v.started_at >= $2)`,[ownerUserId,cutoff])]);const participants=new Map<string,string[]>();for(const row of participantRows.rows){const list=participants.get(row.visit_id)??[];list.push(row.person_id);participants.set(row.visit_id,list);}return visitRows.rows.map(row=>mapVisit(row,participants.get(row.id)??[]));}
export async function getVisit(id:string,ownerUserId:string,options:ReadOptions={}):Promise<Visit|undefined>{const access=await getPlanAccess(ownerUserId);if(getStorageMode()!=="postgres"){const visit=visits.find(v=>v.id===id&&v.ownerUserId===ownerUserId);return visit&&(options.includeArchived||isWithinHistoryWindow(visit.startedAt,access))?visit:undefined;}const cutoff=options.includeArchived||access.fullHistory?null:access.historyCutoff?.toISOString()??null;const[visitRows,participantRows]=await Promise.all([dbQuery<VisitRow>(`select ${visitSelect} from velvet_visits where id=$1 and owner_user_id=$2 and ($3::timestamptz is null or started_at >= $3) limit 1`,[id,ownerUserId,cutoff]),dbQuery<ParticipantRow>(`select visit_id,person_id from velvet_visit_participants where visit_id=$1 and owner_user_id=$2`,[id,ownerUserId])]);const row=visitRows.rows[0];return row?mapVisit(row,participantRows.rows.map(item=>item.person_id)):undefined;}
export async function getPersonVisitStats(personId:string,ownerUserId:string):Promise<PersonVisitStats>{const visible=(await listVisits(ownerUserId)).filter(v=>v.participantIds.includes(personId));const completed=visible.filter(v=>v.endedAt);const durations=completed.map(v=>v.durationMinutes).filter((v):v is number=>typeof v==="number");const paymentCounts=new Map<NonNullable<Visit["paymentMethod"]>,number>();for(const visit of visible)if(visit.paymentMethod)paymentCounts.set(visit.paymentMethod,(paymentCounts.get(visit.paymentMethod)??0)+1);return{visitCount:visible.length,totalSales:visible.reduce((s,v)=>s+(v.salesAmount??0),0),averageStayMinutes:durations.length?Math.round(durations.reduce((s,v)=>s+v,0)/durations.length):undefined,lastVisitAt:visible[0]?.startedAt,commonPaymentMethod:[...paymentCounts.entries()].sort((a,b)=>b[1]-a[1])[0]?.[0],mainNominationCount:visible.filter(v=>v.nominationType==="main").length,inStoreNominationCount:visible.filter(v=>v.nominationType==="in_store").length,openReceivableAmount:visible.filter(v=>v.receivableStatus!=="paid").reduce((s,v)=>s+(v.receivableAmount??0),0),drinkCount:visible.reduce((s,v)=>s+(v.drinkCount??0),0),bottleCount:visible.reduce((s,v)=>s+(v.bottleCount??0),0)};}
export async function getActiveVisitForPerson(personId:string,ownerUserId:string):Promise<Visit|undefined>{return(await listVisits(ownerUserId)).find(v=>!v.endedAt&&v.participantIds.includes(personId));}

function legacyWriteForbidden():never{throw new Error("LEGACY_VISIT_STORE_READ_ONLY");}
export async function startVisit(_personId:string,_ownerUserId:string):Promise<Visit|undefined>{return legacyWriteForbidden();}
export async function addParticipant(_visitId:string,_personId:string,_ownerUserId:string):Promise<Visit|undefined>{return legacyWriteForbidden();}
export async function updateVisit(_visitId:string,_patch:Partial<Visit>,_ownerUserId:string):Promise<Visit|undefined>{return legacyWriteForbidden();}
export async function endVisit(_visitId:string,_ownerUserId:string):Promise<Visit|undefined>{return legacyWriteForbidden();}
