import Link from "next/link";
import { AppHeader } from "@/components/app-header";
import { BottomNav } from "@/components/bottom-nav";
import { getRequestIdentity } from "@/lib/auth/request-identity";
import { listCustomerMemories } from "@/lib/customer-memory-repository";
import { listGrowthCustomers } from "@/lib/growth-engine-customer";
import { listNextActions } from "@/lib/professional-next-action-repository";
import { listProfessionalTimeline, listLatestConversationsByCustomer } from "@/lib/professional-timeline-repository";
import { getPlanAccess, hasVelvetFeature } from "@/lib/plan-access";
import { getOwnerPreferences } from "@/lib/owner-preferences";
import { buildSoonVisitAlert } from "@/lib/soon-alerts";

type PeopleSort = "name" | "recent_visit" | "visit_count" | "soon" | "due_followup" | "open_followup";
type PeopleFilter = "all" | "vip" | "recent" | "followup";
const sortLabels: Record<PeopleSort, string> = { name: "名前順", recent_visit: "最近会った順", visit_count: "来店が多い順", soon: "そろそろ順", due_followup: "フォロー期限が近い順", open_followup: "未対応フォロー順" };
const sortValues: PeopleSort[] = ["name", "recent_visit", "visit_count", "soon", "due_followup", "open_followup"];
const proSortValues = new Set<PeopleSort>(["soon", "due_followup", "open_followup"]); const FAR_FUTURE = "9999-12-31T23:59:59.999Z";
function dueRank(value?: string){if(!value)return FAR_FUTURE;const date=new Date(value);return Number.isFinite(date.getTime())?date.toISOString():FAR_FUTURE}

export default async function PeoplePage({searchParams}:{searchParams:Promise<{q?:string;sort?:string;filter?:string}>}) {
  const {q="",sort="name",filter="all"}=await searchParams; const requestedSort:PeopleSort=sortValues.includes(sort as PeopleSort)?sort as PeopleSort:"name"; const selectedFilter:PeopleFilter=(["all","vip","recent","followup"] as string[]).includes(filter)?filter as PeopleFilter:"all"; const query=q.trim().toLowerCase();
  const {workspaceId,userId,ownerUserId}=await getRequestIdentity(); const [customers,memories,access,preferences]=await Promise.all([listGrowthCustomers(workspaceId,userId),listCustomerMemories(workspaceId,userId),getPlanAccess(ownerUserId),getOwnerPreferences(ownerUserId)]); const proDiscoveryAllowed=hasVelvetFeature(access,"followup.manage"); const selectedSort:PeopleSort=proSortValues.has(requestedSort)&&!proDiscoveryAllowed?"name":requestedSort;
  const memoryByCustomer=new Map(memories.map(m=>[m.customerId,m])); const customerById=new Map(customers.map(c=>[c.customerId,c])); const ids=[...new Set([...customers.map(c=>c.customerId),...memories.map(m=>m.customerId)])];
  const [latest,timelines,nextActionPairs]=await Promise.all([listLatestConversationsByCustomer(workspaceId,userId,ids),Promise.all(ids.map(async id=>[id,await listProfessionalTimeline(workspaceId,userId,id)] as const)),proDiscoveryAllowed?Promise.all(ids.map(async id=>[id,await listNextActions(workspaceId,userId,id)] as const)):Promise.resolve([] as Array<readonly [string, Awaited<ReturnType<typeof listNextActions>>]>)]); const timelineByCustomer=new Map(timelines); const nextByCustomer=new Map(nextActionPairs); const recentCutoff=Date.now()-30*24*60*60*1000;
  const rows=ids.map(customerId=>{const customer=customerById.get(customerId),memory=memoryByCustomer.get(customerId),conversation=latest.get(customerId),timeline=timelineByCustomer.get(customerId)??[];const visits=timeline.filter(item=>item.eventType==="visit");const latestVisit=visits[0]?.occurredAt??"";const nextActions=nextByCustomer.get(customerId)??[];const openNext=nextActions.filter(action=>action.status==="open");const soonAlert=access.soonAlertsAllowed&&preferences.soonAlertsEnabled?buildSoonVisitAlert(customerId,timeline):undefined;const tags=memory?.tags??[];return{customerId,displayName:customer?.displayName??memory?.displayNameSnapshot??"お客様",tags,visitCount:visits.length,latestVisit,isRecent:Boolean(latestVisit&&new Date(latestVisit).getTime()>=recentCutoff),isVip:tags.some(tag=>tag.toUpperCase().includes("VIP")),openFollowupCount:openNext.length,nextDueAt:openNext.map(action=>dueRank(action.dueAt)).sort()[0]??FAR_FUTURE,soonScore:soonAlert?(soonAlert.overdueDays*1000+soonAlert.daysSinceLastVisit):0,soonLabel:soonAlert?`そろそろ · 前回から${soonAlert.daysSinceLastVisit}日`:"",nextAction:openNext[0]?.text??"",memoryText:[memory?.personalityNote,memory?.preferenceNote,memory?.cautionNote,memory?.conversationSummary,memory?.lastInteractionSummary,memory?.nextTopicHint,conversation?.body,conversation?.title].filter(Boolean).join(" ")}});
  function compare(a:typeof rows[number],b:typeof rows[number]){if(selectedSort==="recent_visit")return b.latestVisit.localeCompare(a.latestVisit)||a.displayName.localeCompare(b.displayName,"ja");if(selectedSort==="visit_count")return b.visitCount-a.visitCount||b.latestVisit.localeCompare(a.latestVisit)||a.displayName.localeCompare(b.displayName,"ja");if(selectedSort==="soon")return b.soonScore-a.soonScore||b.latestVisit.localeCompare(a.latestVisit)||a.displayName.localeCompare(b.displayName,"ja");if(selectedSort==="due_followup")return a.nextDueAt.localeCompare(b.nextDueAt)||b.openFollowupCount-a.openFollowupCount||a.displayName.localeCompare(b.displayName,"ja");if(selectedSort==="open_followup")return b.openFollowupCount-a.openFollowupCount||a.nextDueAt.localeCompare(b.nextDueAt)||a.displayName.localeCompare(b.displayName,"ja");return a.displayName.localeCompare(b.displayName,"ja")}
  const filtered=rows.filter(row=>(!query||[row.displayName,...row.tags,row.memoryText].join(" ").toLowerCase().includes(query))&&(selectedFilter==="all"||(selectedFilter==="vip"&&row.isVip)||(selectedFilter==="recent"&&row.isRecent)||(selectedFilter==="followup"&&row.openFollowupCount>0))).sort(compare);
  const filterHref=(value:PeopleFilter)=>`/people?filter=${value}&sort=${selectedSort}${q?`&q=${encodeURIComponent(q)}`:""}`;
  return <main className="shell peopleShell"><AppHeader title="顧客" rightHref="/add" rightLabel="＋"/><div className="peopleIntro"><div><span className="eyebrow">PEOPLE</span><strong>大切な人を、すぐに思い出す。</strong></div><Link href="/search" className="peopleSearchLink">詳しく探す ›</Link></div><form action="/people" method="get" className="stack peopleSearchForm"><input type="hidden" name="filter" value={selectedFilter}/><input className="searchBox" name="q" defaultValue={q} placeholder="名前・特徴・趣味・タグで検索" autoComplete="off"/><div className="customerToolbar" aria-label="顧客フィルター">{([["all","すべて"],["vip","VIP"],["recent","最近会った"],["followup","要フォロー"]] as Array<[PeopleFilter,string]>).map(([value,label])=><Link className={`filterPill${selectedFilter===value?" active":""}`} href={filterHref(value)} key={value}>{label}</Link>)}</div><div className="sortRow"><select className="selectBox" id="sort" name="sort" defaultValue={selectedSort} aria-label="並び替え">{sortValues.map(value=><option value={value} key={value} disabled={proSortValues.has(value)&&!proDiscoveryAllowed}>{sortLabels[value]}{proSortValues.has(value)?" · Pro":""}</option>)}</select><button className="secondaryButton compactButton" type="submit">並び替え</button></div></form><div className="peopleCount">{query?`${filtered.length}件見つかりました`:`${filtered.length}人のお客様`}</div><div className="peopleList">{filtered.map(row=><Link className="personRow customerOpenRow" href={`/people/${row.customerId}`} key={row.customerId}><div className="avatar">{row.displayName.slice(0,1)}</div><div className="personMain"><div className="personName">{row.displayName}{row.isVip&&<span className="vipBadge">♛ VIP</span>}{row.openFollowupCount>0&&<span className="statusBadge">要フォロー</span>}</div><div className="personMeta">{row.latestVisit?`最終接点 ${row.latestVisit.slice(0,10)}`:"まだ接点の記録はありません"}</div>{row.nextAction&&<div className="formHint">次回：{row.nextAction}</div>}{!row.nextAction&&row.tags.length>0&&<div className="formHint">{row.tags.slice(0,3).join(" · ")}</div>}</div><span className="rowChevron">›</span></Link>)}{filtered.length===0&&<div className="card empty peopleEmpty"><span>○</span><strong>条件に合うお客様はいません</strong><small>検索条件を変えるか、新しいお客様を追加してみましょう。</small></div>}</div><BottomNav/></main>;
}
